export enum OrderState {
    PAYMENT_WAITING = 'PAYMENT_WAITING',
    PREPARING = 'PREPARING',
    SHIPPED = 'SHIPPED',
    DELIVERING = 'DELIVERING',
    DELIVERY_COMPLETED = 'DELIVERY_COMPLETED',
    CANCELLED = 'CANCELLED',
}
