plugins {
    id 'java'
    // grpc
    id 'com.google.protobuf' version '0.9.5'
}

group = 'org.heeyeop'
version = '0.0.1-SNAPSHOT'
description = 'grpc-quickstart'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // grpc 라이브러리
    runtimeOnly 'io.grpc:grpc-netty-shaded:1.80.0'
    implementation 'io.grpc:grpc-protobuf:1.80.0'
    implementation 'io.grpc:grpc-stub:1.80.0'

    compileOnly 'jakarta.annotation:jakarta.annotation-api:3.0.0'
}

tasks.named('test') {
    useJUnitPlatform()
}

// grpc 사용하기 위한 설정 추가
protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.25.8"
    }
    plugins {
        grpc {
            artifact = 'io.grpc:protoc-gen-grpc-java:1.80.0'
        }
    }
    generateProtoTasks {
        all()*.plugins {
            grpc {}
        }
    }
}