
services:
  postgres-local:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
    ports:
      - '5442:5432'
    networks:
      - local
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready | grep accepting']
      interval: 1s
      timeout: 5s
      retries: 3

  redis-local:
    image: redis:7-alpine
    ports:
      - '6342:6379'
    networks:
      - local
    depends_on:
      - postgres-local
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
      interval: 1s
      timeout: 3s
      retries: 3

networks:
  local:
    driver: bridge
