services:
  postgres-test:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
    ports:
      - '5453:5432'
    networks:
      - test
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres | grep accepting']
      interval: 1s
      timeout: 5s
      retries: 3

  redis-test:
    image: redis:latest
    ports:
      - '6389:6379'
    networks:
      - test
    depends_on:
      - postgres-test
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
      interval: 1s
      timeout: 3s
      retries: 3

networks:
  test:
    driver: bridge
