version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: express_example_db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: express_example
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
