services:
  redis:
    image: redis:7-alpine
    ports:
      - '6382:6379'
    networks:
      - local
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
      interval: 1s
      timeout: 3s
      retries: 3

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    networks:
      - local
    depends_on:
      - redis

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    networks:
      - local
    depends_on:
      - redis
      - producer

  bullmq-exporter:
    build:
      context: ./exporter
      dockerfile: Dockerfile
    ports:
      - '4001:4001'
    networks:
      - local
    depends_on:
      - redis
      - producer
      - consumer

networks:
  local:
    driver: bridge
