### get secrets
GET http://localhost:8080/secrets

### create secret
POST http://localhost:8080/secrets
content-type: application/json

{
  "filename": "rsa.pem",
  "secretName": "rsa-secret"
}

### delete secret
DELETE http://localhost:8080/secrets/rsa-secret
