apiVersion: v1
kind: Secret
metadata:
  name: pushsecret-example
  namespace: app
stringData:
  best-pokemon-src: "Pikachu"
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-example
  namespace: app
spec:
  updatePolicy: Replace
  deletionPolicy: Delete
  refreshInterval: 1h0m0s
  secretStoreRefs:
    - name: aws-parameter-store
      kind: SecretStore
  selector:
    secret:
      name: pushsecret-example
  template:
    data:
      best-pokemon: "{{ index . \"best-pokemon-src\" | toString | upper }} is the really best!"
  data:
    - conversionStrategy: None
      match:
        secretKey: best-pokemon
        remoteRef:
          remoteKey: /eso-demo/push-secret
          property: best-pokemon-dst
