apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: simple-external-secret
  namespace: app
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: aws-parameter-store
    kind: SecretStore
  target:
    name: simple-secret
    creationPolicy: Owner
  data:
  - secretKey: test
    remoteRef:
      key: /eso-demo/simple-data
      version: "1"
