apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: structured-external-secret2
  namespace: app
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: aws-parameter-store
    kind: SecretStore
  target:
    name: structured-secret2
    creationPolicy: Owner
  data:
  - secretKey: hello
    remoteRef:
      key: /eso-demo/structured-data
      property: hello
