apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: structured-external-secret
  namespace: app
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: aws-parameter-store
    kind: SecretStore
  target:
    name: structured-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: /eso-demo/structured-data
